CREATE DATABASE dkis;

\connect dkis

CREATE TABLE IF NOT EXISTS musical_instrument
(
    id              INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    instrument_name VARCHAR,
    instrument_type VARCHAR,
    brand           VARCHAR,
    price           NUMERIC,
    quantity        INTEGER
);

CREATE TABLE IF NOT EXISTS users
(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username varchar,
    u_password varchar,
    u_role varchar
);

