CREATE DATABASE dkis;

\connect dkis

CREATE TABLE IF NOT EXISTS musical_instrument
(
    id              INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    instrument_name VARCHAR,
    instrument_type VARCHAR,
    brand           VARCHAR,
    price           NUMERIC,
    quantity        INTEGER
);

